# -*- coding: utf-8 -*-
"""VF_LF_L5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dG-wU8cBKe0bxh-3FIhrHzLuui5VefPO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ─────────────────────────────────────────────
# 1. LESA GÖGN
# ─────────────────────────────────────────────
df = pd.read_csv('/content/ID_14.csv', sep=';')
df['date'] = pd.to_datetime(df[['YYYY','MM','DD']].rename(
    columns={'YYYY':'year','MM':'month','DD':'day'}))

mask = (df['date'] >= '1993-10-01') & (df['date'] <= '2023-09-30')
df = df[mask].copy().reset_index(drop=True)
Q = df['qobs'].values

print(f"Fjöldi daga: {len(df)}")
print(f"Meðalrennsli: {Q.mean():.2f} m³/s")


# ─────────────────────────────────────────────
# 2. REIKNA FLOW DURATION CURVE
# ─────────────────────────────────────────────
# Raða rennsli frá hæstu til lægstu
Q_sorted = np.sort(Q)[::-1]
n = len(Q_sorted)

# Reikna hlutfall tíma sem rennsli er yfir hverju gildi (%)
exceedance = np.arange(1, n + 1) / n * 100

# Finna Q5, Q50, Q95 með interpolation
Q5  = np.percentile(Q, 100 - 5)   # 5% exceedance  = hárennsli
Q50 = np.percentile(Q, 100 - 50)  # 50% exceedance = miðgildi
Q95 = np.percentile(Q, 100 - 95)  # 95% exceedance = lágrennsli

# ─────────────────────────────────────────────
# 3. MYND – LANGÆISLÍNA
# ─────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(10, 6))

# Teikna FDC
ax.semilogy(exceedance, Q_sorted, color='steelblue', linewidth=2,
            label='Langæislína rennslis')

# Merkja Q5, Q50, Q95
for q_val, pct, label, color in [
    (Q5,  5,  'Q5 = {:.1f} m³/s'.format(Q5),  'red'),
    (Q50, 50, 'Q50 = {:.1f} m³/s'.format(Q50), 'green'),
    (Q95, 95, 'Q95 = {:.1f} m³/s'.format(Q95), 'orange'),
]:
    ax.axvline(pct, color=color, linestyle='--', linewidth=1.5, alpha=0.7)
    ax.axhline(q_val, color=color, linestyle='--', linewidth=1.5, alpha=0.7)
    ax.plot(pct, q_val, 'o', color=color, markersize=10, zorder=5,
            label=label)

ax.set_title('Langæislína rennslis (Flow Duration Curve)\n'
             'Eystri-Rangá, Tungufoss (ID 14) – 1993–2023', fontsize=13)
ax.set_xlabel('Tímahlutfall sem rennsli er yfir þessu gildi (%)', fontsize=11)
ax.set_ylabel('Rennsli Q (m³/s) – lograskali', fontsize=11)
ax.set_xlim(0, 100)
ax.grid(True, which='both', alpha=0.3)
ax.legend(fontsize=10)

plt.tight_layout()
plt.savefig('flow_duration_curve.png', dpi=150)
plt.show()

# ─────────────────────────────────────────────
# 4. SAMANTEKT
# ─────────────────────────────────────────────
print("\n" + "="*50)
print("SAMANTEKT NIÐURSTAÐNA – LIÐUR 5")
print("="*50)
print(f"Q5  (hárennsli):   {Q5:.2f} m³/s")
print(f"Q50 (miðgildi):    {Q50:.2f} m³/s")
print(f"Q95 (lágrennsli):  {Q95:.2f} m³/s")
print(f"Q5/Q95 hlutfall:   {Q5/Q95:.2f}")
print(f"Hámarksrennsli:    {Q.max():.2f} m³/s")
print(f"Lágmarksrennsli:   {Q.min():.2f} m³/s")
print("="*50)