# -*- coding: utf-8 -*-
"""VF_LV_L8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H9UPnZc51OqO8RFjRon6204aPWJUiwVb
"""

import pandas as pd
import matplotlib.pyplot as plt

# ─────────────────────────────────────────────
# 1. LESA GÖGN
# ─────────────────────────────────────────────
df_q = pd.read_csv("ID_14_discharge.csv", sep=';')
df_met = pd.read_csv("ID_14_meteo.csv", sep=';')

df_q['date'] = pd.to_datetime(df_q['YYYY'].astype(str) + '-' +
                              df_q['MM'].astype(str) + '-' +
                              df_q['DD'].astype(str))

df_met['date'] = pd.to_datetime(df_met['YYYY'].astype(str) + '-' +
                                df_met['MM'].astype(str) + '-' +
                                df_met['DD'].astype(str))

# Sía í verkefnistímabilið
df_q   = df_q[(df_q['date'] >= '1993-10-01') & (df_q['date'] <= '2023-09-30')].copy()
df_met = df_met[(df_met['date'] >= '1993-10-01') & (df_met['date'] <= '2023-09-30')].copy()

# ─────────────────────────────────────────────
# 2. FINNA TOPP RENNSLISATBURÐ
# ─────────────────────────────────────────────
peak_idx  = df_q['qobs'].idxmax()
peak_date = df_q.loc[peak_idx, 'date']
print("Peak date:", peak_date)
print("Peak rennsli:", df_q.loc[peak_idx, 'qobs'], "m³/s")

# Velja tímabil: 10 dagar fyrir og 10 dagar eftir topp
start_date = peak_date - pd.Timedelta(days=10)
end_date   = peak_date + pd.Timedelta(days=10)

# Sía gögn fyrir tímabilið
event_q   = df_q[(df_q['date'] >= start_date) & (df_q['date'] <= end_date)].copy()
event_met = df_met[(df_met['date'] >= start_date) & (df_met['date'] <= end_date)].copy()

# ─────────────────────────────────────────────
# 3. MYND
# ─────────────────────────────────────────────
fig, ax1 = plt.subplots(figsize=(12, 6))

# Rennsli
ax1.plot(event_q['date'], event_q['qobs'], 'b-', linewidth=2, label='Rennsli (Q)')
ax1.set_xlabel("Dagsetning")
ax1.set_ylabel("Rennsli (m³/s)")

# Hitastig á sama ás
ax1.plot(event_met['date'], event_met['2m_temp_mean'], 'r--',
         linewidth=1.5, label='Hitastig (T)')

# Úrkoma á hægri ás
ax2 = ax1.twinx()
ax2.bar(event_met['date'], event_met['prec'], alpha=0.3,
        color='steelblue', label='Úrkoma (P)')
ax2.set_ylabel("Úrkoma (mm)")

# Merkja topp
ax1.axvline(peak_date, color='black', linestyle='--', linewidth=1.5, label='Q peak')

# Legend
ax1.legend(loc='upper left')
ax2.legend(loc='upper right')

plt.title("Greining á rennslisatburði – Eystri-Rangá")
fig.tight_layout()
fig.savefig('flood_event_analysis.png', dpi=150)
plt.show()