# -*- coding: utf-8 -*-
"""VF_LV_L1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kACv1jsPVPiVF-IMF0O0iFzgoXlRAZnr
"""

import pandas as pd

# Les skrána
df = pd.read_csv('/content/Catchment_attributes.csv', sep=';')

# Finna ID 14 - Eystri-Rangá
row = df[df['id'] == 14]

# Sýna ALLAR upplýsingar um vatnasviðið
print(row.T.to_string())