# -*- coding: utf-8 -*-
"""VF_LV_L4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jqd2aVOugjhzG4TfG2p7Na_pOMplR5W_
"""

mean_Q = df_q['qobs'].mean()
mean_P = df_met['prec'].mean()
mean_T = df_met['2m_temp_mean'].mean()

print("Meðal Q:", mean_Q)
print("Meðal P:", mean_P)
print("Meðal T:", mean_T)