# -*- coding: utf-8 -*-
"""VF_LV_L6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mks2JjbytdXYlTUH0cAnNSmxFSibJPq0
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import gumbel_r, lognorm, pearson3

# ─────────────────────────────────────────────
# 1. LESA GÖGN
# ─────────────────────────────────────────────
df_q = pd.read_csv("ID_14_discharge.csv", sep=';')

df_q['date'] = pd.to_datetime(
    df_q['YYYY'].astype(str) + '-' +
    df_q['MM'].astype(str) + '-' +
    df_q['DD'].astype(str)
)

df_q = df_q[(df_q['date'] >= '1993-10-01') & (df_q['date'] <= '2023-09-30')].copy()
df_q['year'] = df_q['date'].dt.year
df_q['month'] = df_q['date'].dt.month

# Finna hæsta rennsli hvers árs
annual_max = df_q.loc[df_q.groupby('year')['qobs'].idxmax()].copy()


# ─────────────────────────────────────────────
# 2. FLÓÐARSTÍÐABUNDIN GREINING
# ─────────────────────────────────────────────
monthly_counts = annual_max['month'].value_counts().sort_index()
monthly_counts = monthly_counts.reindex(range(1, 13), fill_value=0)

fig1, ax1 = plt.subplots(figsize=(8, 5))
monthly_counts.plot(kind='bar', ax=ax1)
ax1.set(title='Árleg hámarksflóð eftir mánuðum – Eystri-Rangá',
        xlabel='Mánuður', ylabel='Fjöldi annual peaks')
ax1.grid(axis='y')
fig1.tight_layout()
fig1.savefig('flood_seasonality.png', dpi=150)

print(monthly_counts)


# ─────────────────────────────────────────────
# 3. LÍKINDADREIFINGAR – GUMBEL, LN3, LP3
# ─────────────────────────────────────────────
q = annual_max['qobs'].dropna().values
q = np.sort(q)
n = len(q)

# Gringorten plotting positions
i = np.arange(1, n + 1)
F_emp = (i - 0.44) / (n + 0.12)
T_emp = 1 / (1 - F_emp)

# Fit dreifingar
params_gum   = gumbel_r.fit(q)
params_logn3 = lognorm.fit(q)
y            = np.log(q)
params_lp3   = pearson3.fit(y)

# Fitted gildi við empirical líkur
q_gum   = gumbel_r.ppf(F_emp, *params_gum)
q_logn3 = lognorm.ppf(F_emp, *params_logn3)
q_lp3   = np.exp(pearson3.ppf(F_emp, *params_lp3))

# RMSE samanburður
rmse_gum   = np.sqrt(np.mean((q - q_gum) ** 2))
rmse_logn3 = np.sqrt(np.mean((q - q_logn3) ** 2))
rmse_lp3   = np.sqrt(np.mean((q - q_lp3) ** 2))

rmse_dict = {'Gumbel': rmse_gum, 'LogNormal 3': rmse_logn3, 'LogPearson 3': rmse_lp3}
best_dist = min(rmse_dict, key=rmse_dict.get)

print(f"\nRMSE Gumbel:       {rmse_gum:.3f}")
print(f"RMSE LogNormal 3:  {rmse_logn3:.3f}")
print(f"RMSE LogPearson 3: {rmse_lp3:.3f}")
print(f"Besta dreifing:    {best_dist}")

# Q10, Q50, Q100
T_ret = np.array([10, 50, 100])
F_ret = 1 - 1 / T_ret

Q_gum   = gumbel_r.ppf(F_ret, *params_gum)
Q_logn3 = lognorm.ppf(F_ret, *params_logn3)
Q_lp3   = np.exp(pearson3.ppf(F_ret, *params_lp3))

print("\nEndurkomutímar:")
for t, a, b, c in zip(T_ret, Q_gum, Q_logn3, Q_lp3):
    print(f"T={t:>3} ár:  Gumbel={a:.2f},  LogNormal3={b:.2f},  LogPearson3={c:.2f}")

# Mynd – líkindadreifingar
T_plot = np.linspace(1.01, max(T_emp.max(), 120), 500)
F_plot = 1 - 1 / T_plot

fig2, ax2 = plt.subplots(figsize=(8, 6))
ax2.scatter(T_emp, q, label='Annual peaks (Gringorten)', zorder=5)
ax2.plot(T_plot, gumbel_r.ppf(F_plot, *params_gum),                  label='Gumbel')
ax2.plot(T_plot, lognorm.ppf(F_plot, *params_logn3),                  label='LogNormal 3')
ax2.plot(T_plot, np.exp(pearson3.ppf(F_plot, *params_lp3)),           label='LogPearson 3')
ax2.set(title='Flóðagreining – Eystri-Rangá',
        xlabel='Endurkomutími T (ár)', ylabel='Rennsli (m³/s)')
ax2.set_xscale('log')
ax2.grid(True, which='both')
ax2.legend()
fig2.tight_layout()
fig2.savefig('flood_frequency.png', dpi=150)


# ─────────────────────────────────────────────
# 4. BOOTSTRAP CONFIDENCE INTERVAL (90%)
# ─────────────────────────────────────────────
n_boot = 1000
boot_q10, boot_q50, boot_q100 = [], [], []

for _ in range(n_boot):
    sample = np.random.choice(q, size=len(q), replace=True)
    sample = np.sort(sample)
    y_boot = np.log(sample)
    params_boot = pearson3.fit(y_boot)
    q_boot = np.exp(pearson3.ppf(F_ret, *params_boot))
    boot_q10.append(q_boot[0])
    boot_q50.append(q_boot[1])
    boot_q100.append(q_boot[2])

ci_q10  = np.percentile(boot_q10,  [5, 95])
ci_q50  = np.percentile(boot_q50,  [5, 95])
ci_q100 = np.percentile(boot_q100, [5, 95])

print(f"\nQ10  90% CI: {ci_q10[0]:.2f} – {ci_q10[1]:.2f} m³/s")
print(f"Q50  90% CI: {ci_q50[0]:.2f} – {ci_q50[1]:.2f} m³/s")
print(f"Q100 90% CI: {ci_q100[0]:.2f} – {ci_q100[1]:.2f} m³/s")

plt.show()