# -*- coding: utf-8 -*-
"""vf_lv_l3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AO79g22PsB2pxb8te0IR8oS7-mtNRY3y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# --- STILLINGAR (Configuration) ---
FILE_PATH = '/content/ID_14.csv'
VALIÐ_TÍMABIL = 1  # Veldu númer tímabils fyrir recession greiningu


# ─────────────────────────────────────────────
# 1. HVERNIG VIÐ LESUM GÖGNIN (Functions)
# ─────────────────────────────────────────────
def load_and_prep_data(filepath):
    df = pd.read_csv(filepath, sep=';')
    df = df.rename(columns={'YYYY': 'year', 'MM': 'month', 'DD': 'day'})
    df['date'] = pd.to_datetime(df[['year', 'month', 'day']])

    # Sía dagsetningar
    mask = (df['date'] >= '1993-10-01') & (df['date'] <= '2023-09-30')
    df = df[mask].copy().reset_index(drop=True)

    # Bæta við vatnsári (Water Year)
    df['water_year'] = df['date'].apply(lambda d: d.year + 1 if d.month >= 10 else d.year)
    return df

def lyne_hollick(Q, alpha=0.925, n_passes=3):
    """Baseflow separation – Lyne-Hollick aðferð."""
    Q = np.array(Q, dtype=float)
    n = len(Q)

    for i in range(n_passes):
        qf = np.zeros(n)
        if i % 2 == 0:  # Áfram (Forward pass)
            qf[0] = Q[0] / 2
            for t in range(1, n):
                qf[t] = alpha * qf[t-1] + (1 + alpha) / 2 * (Q[t] - Q[t-1])
                qf[t] = np.clip(qf[t], 0, Q[t])
        else:           # Afturábak (Backward pass)
            qf[-1] = Q[-1] / 2
            for t in range(n-2, -1, -1):
                qf[t] = alpha * qf[t+1] + (1 + alpha) / 2 * (Q[t] - Q[t+1])
                qf[t] = np.clip(qf[t], 0, Q[t])

        Q_quick = qf

    Qb = np.clip(Q - Q_quick, 0, Q)
    return Qb

def find_recession_periods(Q, min_length=10, max_ratio=0.99):
    """Finnur lækkunartímabil í rennsli."""
    periods = []
    n = len(Q)
    i = 0
    while i < n - min_length:
        if Q[i+1] < Q[i]:
            j = i + 1
            while j < n and Q[j] <= Q[j-1] * max_ratio + 0.01:
                j += 1
            if j - i >= min_length:
                periods.append((i, j))
            i = j
        else:
            i += 1
    return periods

def calculate_k_for_period(Q, start, end):
    """Reiknar recession constant (k) fyrir tiltekið tímabil."""
    q_rec = Q[start:end]
    t = np.arange(len(q_rec))
    slope, intercept = np.polyfit(t, np.log(q_rec), 1)
    k = -1 / slope if slope != 0 else np.nan
    return k, slope, intercept, q_rec, t


# ─────────────────────────────────────────────
# 2. KEYRSLA OG GREINING (Execution)
# ─────────────────────────────────────────────
# Lesa gögn
df = load_and_prep_data(FILE_PATH)
Q = df['qobs'].values
dates = df['date'].values

print(f"Fjöldi daga: {len(df)}")
print(f"Meðalrennsli: {Q.mean():.2f} m³/s | Hámark: {Q.max():.2f} m³/s | Lágmark: {Q.min():.2f} m³/s")

# Baseflow Separation
df['Qb'] = lyne_hollick(Q, alpha=0.925)
df['Qf'] = df['qobs'] - df['Qb']

print("\n--- Baseflow Separation ---")
print(f"Meðal grunnrennsli (Qb): {df['Qb'].mean():.2f} m³/s")
print(f"Meðal yfirborðsrennsli (Qf): {df['Qf'].mean():.2f} m³/s")

# Baseflow Index (BFI) - Optimized with Pandas Groupby
bfi_series = df.groupby('water_year')['Qb'].sum() / df.groupby('water_year')['qobs'].sum()
bfi_df = bfi_series.reset_index(name='BFI')
mean_bfi = bfi_df['BFI'].mean()
print(f"Meðal BFI: {mean_bfi:.3f}")

# Recession Analysis
recession_periods = find_recession_periods(Q, min_length=10)

# Reikna k fyrir ÖLL tímabil til að fá meðaltal/miðgildi (Fixing the bug)
all_k_values = [calculate_k_for_period(Q, s, e)[0] for s, e in recession_periods]
all_k_values = [k for k in all_k_values if k > 0] # Filter out anomalies
mean_k = np.mean(all_k_values)
median_k = np.median(all_k_values)

print(f"\n--- Recession Analysis ---")
print(f"Fjöldi lækkunartímabila: {len(recession_periods)}")
print(f"{'#':<5} {'Upphaf':<15} {'Endir':<15} {'Lengd (dagar)'}")
print("-" * 50)
for i, (start, end) in enumerate(recession_periods):
    print(f"{i+1:<5} {str(dates[start])[:10]:<15} {str(dates[end-1])[:10]:<15} {end - start}")

# Gögn fyrir VALIÐ tímabil
idx = VALIÐ_TÍMABIL - 1
start_idx, end_idx = recession_periods[idx]
k_val, slope, intercept, q_rec, t_rec = calculate_k_for_period(Q, start_idx, end_idx)
q_fit = np.exp(intercept) * np.exp(slope * t_rec)
dates_rec = dates[start_idx:end_idx]

d_start = pd.Timestamp(dates[start_idx]).date()
d_end = pd.Timestamp(dates[end_idx-1]).date()

print(f"\nValið tímabil #{VALIÐ_TÍMABIL}: {d_start} → {d_end}")
print(f"Lengd: {end_idx - start_idx} dagar | Recession constant (k): {k_val:.1f} dagar")


# ─────────────────────────────────────────────
# 3. MYNDRÆN FRAMSETNING (Plotting)
# ─────────────────────────────────────────────
# --- Mynd 1: Baseflow separation 2010 ---
df_2010 = df[df['water_year'] == 2010]
fig1, ax1 = plt.subplots(figsize=(12, 5))
ax1.fill_between(df_2010['date'], df_2010['Qb'], alpha=0.8, color='steelblue', label='Grunnrennsli (Qb)')
ax1.fill_between(df_2010['date'], df_2010['qobs'], df_2010['Qb'], alpha=0.7, color='orange', label='Yfirborðsrennsli (Qf)')
ax1.plot(df_2010['date'], df_2010['qobs'], 'k-', linewidth=0.8, label='Heildarrennsli (Q)')
ax1.set(title='Baseflow separation – Vatnsárið 2010\nEystri-Rangá, Tungufoss (ID 14)', xlabel='Dagsetning', ylabel='Rennsli (m³/s)')
ax1.legend()
ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
plt.xticks(rotation=30)
fig1.tight_layout()
fig1.savefig('baseflow_separation_2010.png', dpi=150)

# --- Mynd 2: BFI súlurit ---
fig2, ax2 = plt.subplots(figsize=(12, 5))
ax2.bar(bfi_df['water_year'], bfi_df['BFI'], color='steelblue', edgecolor='white', linewidth=0.5)
ax2.axhline(mean_bfi, color='red', linestyle='--', linewidth=2, label=f'Meðal BFI = {mean_bfi:.3f}')
ax2.set(title='Baseflow Index (BFI) eftir vatnsárum\nEystri-Rangá, Tungufoss (ID 14)', xlabel='Vatnsár', ylabel='BFI', ylim=(0, 1))
ax2.legend()
fig2.tight_layout()
fig2.savefig('bfi_per_year.png', dpi=150)

# --- Mynd 3: Recession analysis – valið tímabil ---
fig3, axes = plt.subplots(1, 2, figsize=(12, 5))
fig3.suptitle(f'Recession Analysis – Eystri-Rangá (ID 14)\nTímabil: {d_start} → {d_end}', fontsize=13)

axes[0].plot(dates_rec, q_rec, 'b-o', markersize=4, label='Mælt rennsli')
axes[0].plot(dates_rec, q_fit, 'r--', linewidth=2, label=f'Fitted: Q₀·e^(-t/{k_val:.1f})')
axes[0].set(title='Skref 1: Lækkunartímabil', xlabel='Dagsetning', ylabel='Rennsli (m³/s)')
axes[0].legend()
axes[0].xaxis.set_major_formatter(mdates.DateFormatter('%m-%d'))
plt.setp(axes[0].xaxis.get_majorticklabels(), rotation=30)

axes[1].plot(t_rec, np.log(q_rec), 'bo', markersize=5, label='ln(Q) mælt')
axes[1].plot(t_rec, slope * t_rec + intercept, 'r-', linewidth=2, label=f'ln(Q) = {intercept:.2f} + ({slope:.4f})·t\nk = {k_val:.1f} dagar')
axes[1].set(title='Skref 2: ln(Q) sem fall af t', xlabel='Tími t (dagar frá upphafi)', ylabel='ln(Q)')
axes[1].legend()

fig3.tight_layout()
fig3.savefig('recession_analysis.png', dpi=150)
plt.show()

# ─────────────────────────────────────────────
# 4. SAMANTEKT NIÐURSTAÐNA
# ─────────────────────────────────────────────
print("\n" + "="*50)
print("SAMANTEKT NIÐURSTAÐNA – LIÐUR 3")
print("="*50)
print(f"Aðferð: Lyne-Hollick (α = 0.925)")
print(f"Meðal BFI: {mean_bfi:.3f}")
print(f"Recession tímabil: {d_start} → {d_end}")
print(f"Lengd recession tímabils: {end_idx - start_idx} dagar")
print(f"Recession constant á völdnu tímabili (k): {k_val:.1f} dagar")
print(f"Meðal recession constant (k): {mean_k:.1f} dagar")
print(f"Miðgildi recession constant (k): {median_k:.1f} dagar")
print("="*50)