# -*- coding: utf-8 -*-
"""VF_LV_L7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7e8S8uREKlHXw6AP3xqdREs9QCY5CKD
"""

!pip install pymannkendall


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pymannkendall as mk
from scipy.stats import theilslopes

# ─────────────────────────────────────────────
# 1. LESA GÖGN
# ─────────────────────────────────────────────
df = pd.read_csv('/content/ID_14.csv', sep=';')
df['date'] = pd.to_datetime(df[['YYYY','MM','DD']].rename(
    columns={'YYYY':'year','MM':'month','DD':'day'}))

mask = (df['date'] >= '1993-10-01') & (df['date'] <= '2023-09-30')
df = df[mask].copy().reset_index(drop=True)

def get_water_year(date):
    return date.year + 1 if date.month >= 10 else date.year

df['water_year'] = df['date'].apply(get_water_year)
df['month'] = df['date'].dt.month

print("Gögn lesin!")
print(f"Fjöldi daga: {len(df)}")


# ─────────────────────────────────────────────
# 2. LEITNIGREINING – HJÁLPARFALL
# ─────────────────────────────────────────────
def analyze_trend(data, label=""):
    """
    Framkvæmir Modified Mann-Kendall test og Theil-Sen estimator.
    Skilar töflu með niðurstöðum.
    """
    data = np.array(data, dtype=float)
    data = data[~np.isnan(data)]

    if len(data) < 4:
        return None

    # Modified Mann-Kendall (Hamed & Rao, 1998)
    result = mk.hamed_rao_modification_test(data)

    # Theil-Sen hallatala
    x = np.arange(len(data))
    slope, intercept, _, _ = theilslopes(data, x)

    return {
        'Leitni': label,
        'Theil-Sen (m³/s/ár)': round(slope, 4),
        'p-gildi': round(result.p, 4),
        'Marktækt (p<0.05)': '✓ Já' if result.p < 0.05 else '✗ Nei',
        'Z-gildi (MK)': round(result.z, 3),
        'Stefna': result.trend
    }


# ─────────────────────────────────────────────
# 3A. ÁRLEG LEITNI
# ─────────────────────────────────────────────
annual_q = df.groupby('water_year')['qobs'].mean()
years = annual_q.index.values
q_annual = annual_q.values

result_annual = analyze_trend(q_annual, "Árleg")

# ─────────────────────────────────────────────
# 3B. ÁRSTÍÐABUNDIN LEITNI (Vor, Sumar, Haust, Vetur)
# ─────────────────────────────────────────────
seasons = {
    'Vetur (des–feb)': [12, 1, 2],
    'Vor (mar–maí)':   [3, 4, 5],
    'Sumar (jún–ágú)': [6, 7, 8],
    'Haust (sep–nóv)': [9, 10, 11]
}

seasonal_results = []
seasonal_data = {}

for season_name, months in seasons.items():
    season_df = df[df['month'].isin(months)]
    season_annual = season_df.groupby('water_year')['qobs'].mean()
    q_season = season_annual.values
    seasonal_data[season_name] = (season_annual.index.values, q_season)
    res = analyze_trend(q_season, season_name)
    if res:
        seasonal_results.append(res)

# ─────────────────────────────────────────────
# 3C. MÁNAÐARLEG LEITNI
# ─────────────────────────────────────────────
month_names = ['Jan', 'Feb', 'Mar', 'Apr', 'Maí', 'Jún',
               'Júl', 'Ágú', 'Sep', 'Okt', 'Nóv', 'Des']

monthly_results = []
for m in range(1, 13):
    month_df = df[df['month'] == m]
    month_annual = month_df.groupby('water_year')['qobs'].mean()
    res = analyze_trend(month_annual.values, month_names[m-1])
    if res:
        monthly_results.append(res)

df_monthly = pd.DataFrame(monthly_results)

# ─────────────────────────────────────────────
# 4. MYNDIR
# ─────────────────────────────────────────────

# --- Mynd 1: Árleg leitni ---
slope_annual = result_annual['Theil-Sen (m³/s/ár)']
x = np.arange(len(years))
_, intercept, _, _ = theilslopes(q_annual, x)
trend_line = intercept + slope_annual * x

fig, ax = plt.subplots(figsize=(12, 5))
ax.bar(years, q_annual, color='steelblue', alpha=0.7, label='Meðalrennsli per vatnsár')
ax.plot(years, trend_line, 'r-', linewidth=2,
        label=f'Theil-Sen: {slope_annual:.4f} m³/s/ár\n'
              f'p = {result_annual["p-gildi"]:.4f} ({result_annual["Marktækt (p<0.05)"]})')
ax.set_title('Árleg leitni í rennsli\nEystri-Rangá, Tungufoss (ID 14) – 1993–2023',
             fontsize=13)
ax.set_xlabel('Vatnsár')
ax.set_ylabel('Meðalrennsli (m³/s)')
ax.legend(fontsize=10)
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('trend_annual.png', dpi=150)
plt.show()

# --- Mynd 2: Árstíðabundin leitni ---
fig, axes = plt.subplots(2, 2, figsize=(14, 8))
fig.suptitle('Árstíðabundin leitni í rennsli\nEystri-Rangá, Tungufoss (ID 14)',
             fontsize=13)

for ax, (season_name, (s_years, s_q)) in zip(axes.flatten(), seasonal_data.items()):
    res = next(r for r in seasonal_results if r['Leitni'] == season_name)
    slope_s = res['Theil-Sen (m³/s/ár)']
    x_s = np.arange(len(s_years))
    _, int_s, _, _ = theilslopes(s_q, x_s)
    trend_s = int_s + slope_s * x_s

    ax.bar(s_years, s_q, color='steelblue', alpha=0.7)
    ax.plot(s_years, trend_s, 'r-', linewidth=2,
            label=f'Theil-Sen: {slope_s:.4f} m³/s/ár\np = {res["p-gildi"]:.4f} ({res["Marktækt (p<0.05)"]})')
    ax.set_title(season_name, fontsize=11)
    ax.set_xlabel('Vatnsár')
    ax.set_ylabel('Meðalrennsli (m³/s)')
    ax.legend(fontsize=8)
    ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('trend_seasonal.png', dpi=150)
plt.show()


# --- Mynd 3: Mánaðarleg leitni (súlurit) ---
slopes_monthly = [r['Theil-Sen (m³/s/ár)'] for r in monthly_results]
pvals_monthly  = [r['p-gildi'] for r in monthly_results]
colors = ['red' if p < 0.05 else 'steelblue' for p in pvals_monthly]

fig, ax = plt.subplots(figsize=(12, 5))
bars = ax.bar(month_names, slopes_monthly, color=colors, edgecolor='white')
ax.axhline(0, color='black', linewidth=1)
ax.set_title('Mánaðarleg Theil-Sen leitni\nEystri-Rangá, Tungufoss (ID 14)',
             fontsize=13)
ax.set_xlabel('Mánuður')
ax.set_ylabel('Theil-Sen hallatala (m³/s/ár)')
ax.grid(axis='y', alpha=0.3)

# Útskýring
from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='red',      label='Marktækt (p < 0.05)'),
    Patch(facecolor='steelblue', label='Ekki marktækt (p ≥ 0.05)')
]
ax.legend(handles=legend_elements, fontsize=10)
plt.tight_layout()
plt.savefig('trend_monthly.png', dpi=150)
plt.show()

# ─────────────────────────────────────────────
# 5. SAMANTEKT
# ─────────────────────────────────────────────
print("\n" + "="*55)
print("SAMANTEKT NIÐURSTAÐNA – LIÐUR 7")
print("="*55)
print(f"\nÁRLEG LEITNI:")
print(f"  Theil-Sen: {result_annual['Theil-Sen (m³/s/ár)']:.4f} m³/s/ár")
print(f"  p-gildi:   {result_annual['p-gildi']:.4f}  {result_annual['Marktækt (p<0.05)']}")
print(f"\nÁRSTÍÐABUNDIN LEITNI:")
for r in seasonal_results:
    print(f"  {r['Leitni']:<22}: {r['Theil-Sen (m³/s/ár)']:+.4f} m³/s/ár  p={r['p-gildi']:.4f}  {r['Marktækt (p<0.05)']}")
print(f"\nMÁNAÐARLEG LEITNI:")
for r in monthly_results:
    print(f"  {r['Leitni']:<6}: {r['Theil-Sen (m³/s/ár)']:+.4f} m³/s/ár  p={r['p-gildi']:.4f}  {r['Marktækt (p<0.05)']}")
print("="*55)