# -*- coding: utf-8 -*-
"""VF_LV_L2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1is8MvNSv6ZWw-0QAJGuvEz7V7Ls6l5fg
"""

import pandas as pd
import matplotlib.pyplot as plt

# --- LESA RENNSLI ---
df_q = pd.read_csv("ID_14_discharge.csv", sep=';')

df_q['date'] = pd.to_datetime(
    df_q['YYYY'].astype(str) + '-' +
    df_q['MM'].astype(str) + '-' +
    df_q['DD'].astype(str)
)

df_q = df_q[(df_q['date'] >= '1993-10-01') & (df_q['date'] <= '2023-09-30')].copy()
df_q['doy'] = df_q['date'].dt.dayofyear

# --- LESA VEÐUR ---
df_met = pd.read_csv("ID_14_meteo.csv", sep=';')

df_met['date'] = pd.to_datetime(
    df_met['YYYY'].astype(str) + '-' +
    df_met['MM'].astype(str) + '-' +
    df_met['DD'].astype(str)
)

df_met = df_met[(df_met['date'] >= '1993-10-01') & (df_met['date'] <= '2023-09-30')].copy()
df_met['doy'] = df_met['date'].dt.dayofyear

# --- REIKNA MEÐALTALSÁR ---
clim_q = df_q.groupby('doy')['qobs'].mean().reset_index()
clim_p = df_met.groupby('doy')['prec'].mean().reset_index()
clim_t = df_met.groupby('doy')['2m_temp_mean'].mean().reset_index()

# --- MYND 1: RENNSLI ---
fig1, ax1 = plt.subplots(figsize=(10, 4))
ax1.plot(clim_q['doy'], clim_q['qobs'])
ax1.set(title='Meðaltalsár rennslis – Eystri-Rangá',
        xlabel='Dagur árs', ylabel='Rennsli (m³/s)')
ax1.grid()
fig1.tight_layout()
fig1.savefig('medaltalsar_rennsli.png', dpi=150)

# --- MYND 2: ÚRKOMA ---
fig2, ax2 = plt.subplots(figsize=(10, 4))
ax2.plot(clim_p['doy'], clim_p['prec'])
ax2.set(title='Meðaltalsár úrkomu – Eystri-Rangá',
        xlabel='Dagur árs', ylabel='Úrkoma (mm/dag)')
ax2.grid()
fig2.tight_layout()
fig2.savefig('medaltalsar_urkoma.png', dpi=150)

# --- MYND 3: HITASTIG ---
fig3, ax3 = plt.subplots(figsize=(10, 4))
ax3.plot(clim_t['doy'], clim_t['2m_temp_mean'])
ax3.set(title='Meðaltalsár hitastigs – Eystri-Rangá',
        xlabel='Dagur árs', ylabel='Hitastig (°C)')
ax3.grid()
fig3.tight_layout()
fig3.savefig('medaltalsar_hitastig.png', dpi=150)

plt.show()